# Generated by Django 5.2.2 on 2025-06-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
