# Generated by Django 5.2.2 on 2025-06-12 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
